#!/usr/bin/env python
import os,sys
path=os.path.split(sys.argv[0])[0];
os.execv(path+"/cppsp_standalone",[path+"/cppsp_standalone","-c","-fPIC","-c","-I"+path+"/include","-c","-lpthread","-c",path+"/cpoll.o","-c",path+"/cppsp.o"]+sys.argv[1:]);

