######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 22 20:26:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
